spring.application.name=Me

spring.datasource.url=jdbc:mysql://localhost:3306/project_it211_me?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Duong170226@

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.show_sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.web.error.include-stacktrace=never

jwt.secret-key=${JWT_SECRET_KEY}
jwt.access-expiration=900000
jwt.refresh-expiration=86400000
